/**
 * Comprehensive embedded word lists for English and French anagram / Scrabble solver
 */

export const EN_DICTIONARY: string[] = [
  // 2-letter words
  'aa', 'ab', 'ad', 'ae', 'ag', 'ah', 'ai', 'al', 'am', 'an', 'ar', 'as', 'at', 'aw', 'ax', 'ay',
  'ba', 'be', 'bi', 'bo', 'by', 'de', 'do', 'ed', 'ef', 'eh', 'el', 'em', 'en', 'er', 'es', 'et',
  'ex', 'fa', 'go', 'ha', 'he', 'hi', 'hm', 'ho', 'id', 'if', 'in', 'is', 'it', 'jo', 'ka', 'ki',
  'la', 'li', 'lo', 'ma', 'me', 'mi', 'mm', 'mo', 'mu', 'my', 'na', 'ne', 'no', 'nu', 'od', 'oe',
  'of', 'oh', 'oi', 'ok', 'om', 'on', 'op', 'or', 'os', 'ow', 'ox', 'oy', 'pa', 'pe', 'pi', 'qi',
  're', 'sh', 'si', 'so', 'ta', 'ti', 'to', 'uh', 'um', 'un', 'up', 'us', 'ut', 'we', 'wo', 'xi',
  'xu', 'ya', 'ye', 'yo', 'za',

  // 3-letter words
  'ace', 'act', 'add', 'ado', 'aft', 'age', 'ago', 'aid', 'aim', 'air', 'ale', 'all', 'amp', 'and',
  'ant', 'any', 'ape', 'app', 'apt', 'arc', 'are', 'ark', 'arm', 'art', 'ash', 'ask', 'asp', 'ate',
  'awe', 'axe', 'bad', 'bag', 'ban', 'bar', 'bat', 'bay', 'bed', 'bee', 'beg', 'bet', 'bid', 'big',
  'bin', 'bit', 'boa', 'bob', 'bog', 'boo', 'bot', 'bow', 'box', 'boy', 'bra', 'bud', 'bug', 'bum',
  'bus', 'but', 'buy', 'bye', 'cab', 'cam', 'can', 'cap', 'car', 'cat', 'caw', 'cob', 'cod', 'cog',
  'con', 'coo', 'cop', 'cot', 'cow', 'cox', 'coy', 'cry', 'cub', 'cue', 'cup', 'cut', 'dab', 'dad',
  'dam', 'dan', 'day', 'den', 'dew', 'die', 'dig', 'dim', 'din', 'dip', 'doc', 'doe', 'dog', 'don',
  'dot', 'dry', 'dub', 'due', 'dug', 'duo', 'dye', 'ear', 'eat', 'ebb', 'eel', 'egg', 'ego', 'elf',
  'elk', 'elm', 'emu', 'end', 'eon', 'era', 'eve', 'eye', 'fan', 'far', 'fat', 'fax', 'fed', 'fee',
  'few', 'fig', 'fin', 'fir', 'fit', 'fix', 'fly', 'foe', 'fog', 'for', 'fox', 'fry', 'fun', 'fur',
  'gag', 'gal', 'gap', 'gas', 'gel', 'gem', 'get', 'gin', 'god', 'got', 'gum', 'gun', 'gut', 'guy',
  'gym', 'had', 'ham', 'has', 'hat', 'hay', 'hem', 'hen', 'her', 'hex', 'hey', 'hid', 'him', 'hip',
  'his', 'hit', 'hog', 'hop', 'hot', 'how', 'hub', 'hue', 'hug', 'hum', 'hut', 'ice', 'icy', 'ill',
  'imp', 'ink', 'inn', 'ion', 'ire', 'irk', 'its', 'ivy', 'jab', 'jag', 'jam', 'jar', 'jaw', 'jay',
  'jet', 'jig', 'job', 'jog', 'jot', 'joy', 'jug', 'jut', 'keg', 'key', 'kid', 'kin', 'kip', 'kit',
  'lab', 'lad', 'lag', 'lap', 'law', 'lay', 'lea', 'led', 'leg', 'let', 'lid', 'lie', 'lip', 'lit',
  'log', 'lot', 'low', 'mad', 'man', 'map', 'mat', 'max', 'may', 'men', 'met', 'mid', 'mix', 'mob',
  'mom', 'mop', 'mud', 'mug', 'nab', 'nag', 'nap', 'net', 'new', 'nil', 'nip', 'nod', 'nor', 'not',
  'now', 'nut', 'oak', 'oar', 'oat', 'odd', 'ode', 'off', 'oft', 'oil', 'old', 'one', 'opt', 'orb',
  'ore', 'our', 'out', 'owl', 'own', 'pad', 'pal', 'pan', 'par', 'pat', 'paw', 'pay', 'pea', 'peg',
  'pen', 'pet', 'pew', 'pie', 'pig', 'pin', 'pip', 'pit', 'ply', 'pod', 'pop', 'pot', 'pro', 'pry',
  'pub', 'pug', 'pun', 'pup', 'pus', 'put', 'rag', 'ram', 'ran', 'rap', 'rat', 'raw', 'ray', 'red',
  'rib', 'rid', 'rig', 'rim', 'rip', 'rob', 'rod', 'roe', 'rot', 'row', 'rub', 'rug', 'rum', 'run',
  'rut', 'rye', 'sad', 'sag', 'sap', 'sat', 'saw', 'say', 'sea', 'see', 'set', 'sew', 'she', 'shy',
  'sin', 'sip', 'sir', 'sit', 'six', 'ski', 'sky', 'sly', 'sob', 'sod', 'son', 'sop', 'sow', 'soy',
  'spa', 'spy', 'sub', 'sue', 'sum', 'sun', 'tab', 'tad', 'tag', 'tan', 'tap', 'tar', 'tea', 'ten',
  'the', 'tie', 'tin', 'tip', 'toe', 'ton', 'top', 'tow', 'toy', 'try', 'tub', 'tug', 'two', 'urn',
  'use', 'van', 'vat', 'vet', 'via', 'vow', 'war', 'was', 'wax', 'way', 'web', 'wed', 'wee', 'wet',
  'who', 'why', 'wig', 'win', 'wit', 'won', 'woo', 'wow', 'yak', 'yam', 'yap', 'yaw', 'yea', 'yes',
  'yet', 'yew', 'yin', 'yip', 'you', 'zap', 'zed', 'zen', 'zip', 'zoo',

  // 4-letter words
  'able', 'acid', 'aged', 'also', 'area', 'army', 'away', 'baby', 'back', 'ball', 'band', 'bank',
  'base', 'bath', 'bear', 'beat', 'been', 'beer', 'bell', 'belt', 'best', 'bill', 'bird', 'blow',
  'blue', 'boat', 'body', 'bomb', 'bond', 'bone', 'book', 'boom', 'born', 'boss', 'both', 'bowl',
  'bulk', 'burn', 'bush', 'busy', 'call', 'calm', 'came', 'camp', 'card', 'care', 'case', 'cash',
  'cast', 'cell', 'chat', 'chip', 'city', 'club', 'coal', 'coat', 'code', 'cold', 'come', 'cook',
  'cool', 'cope', 'copy', 'core', 'cost', 'crew', 'crop', 'dark', 'data', 'date', 'dawn', 'days',
  'dead', 'deal', 'dean', 'dear', 'debt', 'deep', 'deny', 'desk', 'dial', 'diet', 'disc', 'disk',
  'does', 'done', 'door', 'dose', 'down', 'draw', 'drew', 'drop', 'drug', 'dual', 'duke', 'dust',
  'duty', 'each', 'earn', 'ease', 'east', 'easy', 'edge', 'edit', 'else', 'even', 'ever', 'evil',
  'exit', 'face', 'fact', 'fail', 'fair', 'fall', 'farm', 'fast', 'fate', 'fear', 'feed', 'feel',
  'feet', 'fell', 'felt', 'file', 'fill', 'film', 'find', 'fine', 'fire', 'firm', 'fish', 'five',
  'flat', 'flow', 'food', 'foot', 'ford', 'form', 'fort', 'four', 'free', 'from', 'fuel', 'full',
  'fund', 'gain', 'game', 'gate', 'gave', 'gear', 'gene', 'gift', 'girl', 'give', 'glad', 'goal',
  'goes', 'gold', 'golf', 'gone', 'good', 'gray', 'grew', 'grey', 'grow', 'gulf', 'hair', 'half',
  'hall', 'hand', 'hang', 'hard', 'harm', 'hate', 'have', 'head', 'hear', 'heat', 'held', 'hell',
  'help', 'here', 'hero', 'high', 'hill', 'hire', 'hold', 'hole', 'holy', 'home', 'hope', 'host',
  'hour', 'huge', 'hung', 'hunt', 'hurt', 'icon', 'idea', 'inch', 'into', 'iron', 'item', 'jack',
  'jane', 'jean', 'john', 'join', 'jump', 'jury', 'just', 'keen', 'keep', 'kent', 'kept', 'kick',
  'kill', 'kind', 'king', 'knee', 'knew', 'know', 'lack', 'lady', 'laid', 'lake', 'land', 'lane',
  'last', 'late', 'lead', 'left', 'less', 'life', 'lift', 'like', 'line', 'link', 'list', 'live',
  'load', 'loan', 'lock', 'logo', 'long', 'look', 'lord', 'lose', 'loss', 'lost', 'love', 'luck',
  'made', 'mail', 'main', 'make', 'male', 'many', 'mark', 'mass', 'matt', 'meal', 'mean', 'meat',
  'meet', 'menu', 'mere', 'mike', 'mile', 'milk', 'mill', 'mind', 'mine', 'miss', 'mode', 'mood',
  'moon', 'more', 'most', 'move', 'much', 'must', 'name', 'navy', 'near', 'neck', 'need', 'news',
  'next', 'nice', 'nick', 'nine', 'node', 'none', 'nose', 'note', 'okay', 'once', 'only', 'onto',
  'open', 'oral', 'over', 'pace', 'pack', 'page', 'paid', 'pain', 'pair', 'palm', 'park', 'part',
  'pass', 'past', 'path', 'peak', 'peer', 'pick', 'pile', 'pine', 'pink', 'pipe', 'plan', 'play',
  'plot', 'plug', 'plus', 'poll', 'pool', 'poor', 'port', 'post', 'pull', 'pure', 'push', 'race',
  'rail', 'rain', 'rank', 'rare', 'rate', 'read', 'real', 'rear', 'rely', 'rent', 'rest', 'rice',
  'rich', 'ride', 'ring', 'rise', 'risk', 'road', 'rock', 'role', 'roll', 'roof', 'room', 'root',
  'rose', 'rule', 'rush', 'safe', 'said', 'sake', 'sale', 'salt', 'same', 'sand', 'save', 'seat',
  'seed', 'seek', 'seem', 'seen', 'self', 'sell', 'send', 'sent', 'sept', 'ship', 'shop', 'shot',
  'show', 'shut', 'sick', 'side', 'sign', 'site', 'size', 'skin', 'slip', 'slow', 'snow', 'soft',
  'soil', 'sold', 'sole', 'some', 'song', 'soon', 'sort', 'soul', 'spot', 'star', 'stay', 'step',
  'stop', 'such', 'suit', 'sure', 'take', 'tale', 'talk', 'tall', 'tank', 'tape', 'task', 'team',
  'tech', 'tell', 'tend', 'term', 'test', 'text', 'than', 'that', 'them', 'then', 'they', 'thin',
  'this', 'thus', 'till', 'time', 'tiny', 'told', 'toll', 'tone', 'tony', 'took', 'tool', 'tour',
  'town', 'tree', 'trip', 'true', 'tune', 'turn', 'twin', 'type', 'unit', 'upon', 'used', 'user',
  'vary', 'vast', 'very', 'vice', 'view', 'vote', 'wage', 'wait', 'wake', 'walk', 'wall', 'want',
  'ward', 'warm', 'warn', 'wash', 'wave', 'ways', 'weak', 'wear', 'week', 'well', 'went', 'were',
  'west', 'what', 'when', 'whom', 'wide', 'wife', 'wild', 'will', 'wind', 'wine', 'wing', 'wire',
  'wise', 'wish', 'with', 'wood', 'word', 'wore', 'work', 'yard', 'yeah', 'year', 'your', 'zero',
  'zone',

  // 5-letter words
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again', 'agent',
  'agree', 'ahead', 'alarm', 'album', 'alert', 'alike', 'alive', 'allow', 'alone', 'along', 'alter',
  'among', 'anger', 'angle', 'angry', 'apart', 'apple', 'apply', 'arena', 'argue', 'arise', 'array',
  'aside', 'asset', 'audio', 'audit', 'avoid', 'award', 'aware', 'badly', 'baker', 'bases', 'basic',
  'basis', 'beach', 'began', 'begin', 'begun', 'being', 'below', 'bench', 'billy', 'birth', 'black',
  'blame', 'blind', 'block', 'blood', 'board', 'boost', 'booth', 'bound', 'brain', 'brand', 'bread',
  'break', 'breed', 'brief', 'bring', 'broad', 'broke', 'brown', 'build', 'built', 'buyer', 'cable',
  'calif', 'carry', 'catch', 'cause', 'chain', 'chair', 'chart', 'chase', 'cheap', 'check', 'chest',
  'chief', 'child', 'china', 'chose', 'civil', 'claim', 'class', 'clean', 'clear', 'click', 'clock',
  'close', 'coach', 'coast', 'could', 'count', 'court', 'cover', 'craft', 'crash', 'cream', 'crime',
  'cross', 'crowd', 'crown', 'curve', 'cycle', 'daily', 'dance', 'dated', 'dealt', 'death', 'debut',
  'delay', 'depth', 'doing', 'doubt', 'dozen', 'draft', 'drama', 'drawn', 'dream', 'dress', 'drill',
  'drink', 'drive', 'drove', 'dying', 'eager', 'early', 'earth', 'eight', 'elite', 'empty', 'enemy',
  'enjoy', 'enter', 'entry', 'equal', 'error', 'event', 'every', 'exact', 'exist', 'extra', 'faith',
  'false', 'fault', 'fiber', 'field', 'fifth', 'fifty', 'fight', 'final', 'first', 'fixed', 'flash',
  'fleet', 'floor', 'fluid', 'focus', 'force', 'forth', 'forty', 'forum', 'found', 'frame', 'frank',
  'fraud', 'fresh', 'front', 'fruit', 'fully', 'funny', 'giant', 'given', 'glass', 'globe', 'going',
  'grace', 'grade', 'grand', 'grant', 'grass', 'great', 'green', 'gross', 'group', 'grown', 'guard',
  'guess', 'guest', 'guide', 'happy', 'harry', 'heart', 'heavy', 'hence', 'henry', 'horse', 'hotel',
  'house', 'human', 'ideal', 'image', 'imply', 'index', 'inner', 'input', 'issue', 'japan', 'jimmy',
  'joint', 'jones', 'judge', 'known', 'label', 'large', 'laser', 'later', 'laugh', 'layer', 'learn',
  'lease', 'least', 'leave', 'legal', 'level', 'lewis', 'light', 'limit', 'links', 'lives', 'local',
  'logic', 'loose', 'lower', 'lucky', 'lunch', 'lying', 'magic', 'major', 'maker', 'march', 'maria',
  'match', 'maybe', 'mayor', 'meant', 'media', 'metal', 'might', 'minor', 'minus', 'mixed', 'model',
  'money', 'month', 'moral', 'motor', 'mount', 'mouse', 'mouth', 'movie', 'music', 'needs', 'never',
  'newly', 'night', 'noise', 'north', 'noted', 'novel', 'nurse', 'occur', 'ocean', 'offer', 'often',
  'order', 'other', 'ought', 'paint', 'panel', 'paper', 'party', 'peace', 'peter', 'phase', 'phone',
  'photo', 'piece', 'pilot', 'pitch', 'place', 'plain', 'plane', 'plant', 'plate', 'point', 'pound',
  'power', 'press', 'price', 'pride', 'prime', 'print', 'prior', 'prize', 'proof', 'proud', 'prove',
  'queen', 'quick', 'quiet', 'quite', 'radio', 'raise', 'range', 'rapid', 'ratio', 'reach', 'ready',
  'refer', 'right', 'rival', 'river', 'robin', 'roger', 'roman', 'rough', 'round', 'route', 'royal',
  'rural', 'scale', 'scene', 'scope', 'score', 'sense', 'serve', 'seven', 'shall', 'shape', 'share',
  'sharp', 'sheet', 'shelf', 'shell', 'shift', 'shirt', 'shock', 'shoot', 'short', 'shown', 'sight',
  'since', 'sixth', 'sixty', 'sized', 'skill', 'sleep', 'slide', 'small', 'smart', 'smile', 'smith',
  'smoke', 'solid', 'solve', 'sorry', 'sound', 'south', 'space', 'spare', 'speak', 'speed', 'spend',
  'spent', 'split', 'spoke', 'sport', 'staff', 'stage', 'stake', 'stand', 'start', 'state', 'steam',
  'steel', 'stick', 'still', 'stock', 'stone', 'stood', 'store', 'storm', 'story', 'strip', 'stuck',
  'study', 'stuff', 'style', 'sugar', 'suite', 'super', 'sweet', 'table', 'taken', 'taste', 'taxes',
  'teach', 'teeth', 'terry', 'texas', 'thank', 'theft', 'their', 'theme', 'there', 'these', 'thick',
  'thing', 'think', 'third', 'those', 'three', 'threw', 'throw', 'tight', 'times', 'tired', 'title',
  'today', 'topic', 'total', 'touch', 'tough', 'tower', 'track', 'trade', 'train', 'treat', 'trend',
  'trial', 'tried', 'tries', 'truck', 'truly', 'trust', 'truth', 'twice', 'under', 'undue', 'union',
  'unity', 'until', 'upper', 'upset', 'urban', 'usage', 'usual', 'valid', 'value', 'video', 'virus',
  'visit', 'vital', 'voice', 'waste', 'watch', 'water', 'wheel', 'where', 'which', 'while', 'white',
  'whole', 'whose', 'widely', 'woman', 'world', 'worry', 'worse', 'worst', 'worth', 'would', 'wound',
  'write', 'wrong', 'wrote', 'yield', 'young', 'youth',

  // 6-letter words & Anagram Target Favorites
  'abroad', 'accept', 'access', 'across', 'acting', 'action', 'active', 'actual', 'advice', 'advise',
  'afford', 'afraid', 'agency', 'agenda', 'almost', 'always', 'amount', 'animal', 'annual', 'answer',
  'anyone', 'anyway', 'appeal', 'appear', 'around', 'arrive', 'artist', 'aspect', 'assess', 'assist',
  'assume', 'attack', 'attend', 'august', 'author', 'avenue', 'backed', 'barely', 'battle', 'beauty',
  'became', 'become', 'before', 'behalf', 'behind', 'belief', 'belong', 'berlin', 'better', 'beyond',
  'bishop', 'border', 'borrow', 'bother', 'bottle', 'bottom', 'bought', 'branch', 'breath', 'bridge',
  'bright', 'broken', 'budget', 'burden', 'bureau', 'button', 'camera', 'cancer', 'cannot', 'carbon',
  'career', 'castle', 'casual', 'caught', 'center', 'centre', 'chance', 'change', 'chapel', 'charge',
  'choice', 'choose', 'chosen', 'church', 'cinema', 'circle', 'client', 'closed', 'closer', 'coffee',
  'column', 'combat', 'coming', 'common', 'comply', 'copper', 'corner', 'costly', 'county', 'couple',
  'course', 'covers', 'create', 'credit', 'crisis', 'custom', 'damage', 'danger', 'dealer', 'debate',
  'decade', 'decide', 'defeat', 'defend', 'define', 'degree', 'demand', 'depend', 'deputy', 'desert',
  'design', 'desire', 'detail', 'detect', 'device', 'differ', 'dinner', 'direct', 'doctor', 'dollar',
  'domain', 'double', 'driven', 'driver', 'during', 'easily', 'eating', 'editor', 'effect', 'effort',
  'eighth', 'either', 'eleven', 'emerge', 'empire', 'employ', 'enable', 'ending', 'energy', 'engage',
  'engine', 'enough', 'ensure', 'entire', 'entity', 'equity', 'escape', 'estate', 'ethnic', 'exceed',
  'except', 'excess', 'expand', 'expect', 'expert', 'export', 'extend', 'extent', 'fabric', 'facing',
  'factor', 'failed', 'fairly', 'fallen', 'family', 'famous', 'father', 'fellow', 'female', 'figure',
  'filing', 'finger', 'finish', 'fiscal', 'flight', 'flying', 'follow', 'forced', 'forest', 'forget',
  'formal', 'format', 'former', 'foster', 'fought', 'fourth', 'french', 'friend', 'future', 'garden',
  'gather', 'gender', 'german', 'global', 'golden', 'ground', 'growth', 'guilty', 'handed', 'handle',
  'happen', 'hardly', 'headed', 'health', 'height', 'hidden', 'holder', 'honest', 'impact', 'import',
  'income', 'indeed', 'injury', 'inside', 'intend', 'intent', 'invest', 'island', 'itself', 'jersey',
  'joseph', 'junior', 'killed', 'labour', 'latest', 'latter', 'launch', 'lawyer', 'leader', 'league',
  'leaves', 'legacy', 'length', 'lesson', 'letter', 'lights', 'likely', 'linked', 'listen', 'little',
  'living', 'london', 'losing', 'lucent', 'luxury', 'mainly', 'making', 'manage', 'manner', 'manual',
  'margin', 'marine', 'marked', 'market', 'martin', 'master', 'matter', 'mature', 'medium', 'member',
  'memory', 'mental', 'merely', 'merger', 'method', 'middle', 'miller', 'mining', 'minute', 'mirror',
  'mobile', 'modern', 'modify', 'module', 'moment', 'morris', 'mostly', 'mother', 'motion', 'moving',
  'murder', 'museum', 'mutual', 'myself', 'narrow', 'nation', 'native', 'nature', 'nearly', 'nights',
  'nobody', 'normal', 'notice', 'notion', 'number', 'object', 'obtain', 'office', 'offset', 'online',
  'option', 'orange', 'origin', 'output', 'oxford', 'packed', 'palace', 'parent', 'partly', 'patent',
  'people', 'period', 'permit', 'person', 'phrase', 'picked', 'planet', 'player', 'please', 'plenty',
  'pocket', 'police', 'policy', 'prefer', 'pretty', 'prince', 'prison', 'profit', 'proper', 'proven',
  'public', 'pursue', 'raised', 'random', 'rarely', 'rather', 'rating', 'reader', 'really', 'reason',
  'recall', 'recent', 'record', 'reduce', 'reform', 'regard', 'regime', 'region', 'relate', 'relief',
  'remain', 'remote', 'remove', 'repair', 'repeat', 'replay', 'report', 'rescue', 'resort', 'result',
  'retail', 'retain', 'return', 'reveal', 'revenue', 'review', 'reward', 'riding', 'rising', 'robust',
  'roller', 'romance', 'safely', 'safety', 'salary', 'sample', 'saving', 'scheme', 'school', 'screen',
  'search', 'season', 'second', 'secret', 'sector', 'secure', 'seeing', 'select', 'seller', 'senior',
  'series', 'server', 'settle', 'severe', 'sexually', 'shadow', 'silent', 'silver', 'simple', 'simply',
  'single', 'sister', 'slight', 'smooth', 'social', 'solely', 'sought', 'source', 'soviet', 'speech',
  'spirit', 'spoken', 'spread', 'spring', 'square', 'stable', 'status', 'steady', 'stolen', 'strain',
  'stream', 'street', 'stress', 'strict', 'strike', 'string', 'strong', 'struck', 'studio', 'submit',
  'sudden', 'suffer', 'summer', 'summit', 'supply', 'surely', 'survey', 'switch', 'symbol', 'system',
  'taking', 'talent', 'target', 'taught', 'tenant', 'tender', 'tennis', 'thanks', 'theory', 'thirty',
  'though', 'threat', 'thrown', 'ticket', 'timely', 'timing', 'tissue', 'toward', 'travel', 'treaty',
  'trying', 'twelve', 'twenty', 'unable', 'unique', 'united', 'unless', 'unlike', 'update', 'useful',
  'valley', 'varied', 'vendor', 'versus', 'victim', 'vision', 'visual', 'volume', 'walker', 'wealth',
  'weekly', 'weight', 'wholly', 'window', 'winner', 'winter', 'within', 'wonder', 'worker', 'wright',
  'writer', 'yellow',

  // 7-8-9 letter words
  'ability', 'absence', 'academy', 'account', 'achieve', 'acquire', 'address', 'advance', 'adverse',
  'advised', 'adviser', 'against', 'airline', 'airport', 'alcohol', 'alleged', 'already', 'analyst',
  'ancient', 'another', 'anxiety', 'anxious', 'anybody', 'applied', 'arrange', 'arrival', 'article',
  'assault', 'assumed', 'athlete', 'attempt', 'attract', 'auction', 'average', 'backing', 'balance',
  'banking', 'barrier', 'battery', 'bearing', 'beating', 'because', 'bedroom', 'believe', 'beneath',
  'benefit', 'besides', 'between', 'billion', 'binding', 'brother', 'brought', 'burning', 'cabinet',
  'caliber', 'calling', 'capable', 'capital', 'captain', 'caption', 'capture', 'careful', 'carrier',
  'caution', 'ceiling', 'central', 'centric', 'century', 'certain', 'chamber', 'channel', 'chapter',
  'charity', 'charlie', 'charter', 'checked', 'chicken', 'chronic', 'circuit', 'classic', 'climate',
  'closing', 'closure', 'clothes', 'collect', 'college', 'combine', 'comfort', 'command', 'comment',
  'compact', 'company', 'compare', 'compete', 'complex', 'concept', 'concern', 'concert', 'conduct',
  'confirm', 'connect', 'consent', 'consist', 'contact', 'contain', 'content', 'contest', 'context',
  'control', 'convert', 'correct', 'council', 'counsel', 'counter', 'country', 'crucial', 'crystal',
  'culture', 'current', 'cutting', 'dealing', 'decided', 'decline', 'default', 'defence', 'deficit',
  'deliver', 'density', 'deposit', 'desktop', 'despite', 'destroy', 'develop', 'devoted', 'diamond',
  'digital', 'discuss', 'disease', 'display', 'dispute', 'distant', 'diverse', 'divided', 'drawing',
  'driving', 'dynamic', 'economy', 'edition', 'elderly', 'element', 'engaged', 'enhance', 'enjoyed',
  'enormous', 'entered', 'entitle', 'episode', 'equally', 'essence', 'evening', 'evident', 'exactly',
  'examine', 'example', 'excited', 'exclude', 'execute', 'exhaust', 'exhibit', 'expense', 'explain',
  'explore', 'express', 'extreme', 'factory', 'faculty', 'failing', 'failure', 'fashion', 'feature',
  'federal', 'feeling', 'fiction', 'fifteen', 'filling', 'finance', 'finding', 'fishing', 'fitness',
  'foreign', 'forever', 'formula', 'fortune', 'forward', 'founder', 'freedom', 'further', 'gallery',
  'gateway', 'general', 'genetic', 'genuine', 'gigabit', 'glasses', 'glimpse', 'glorious', 'governor',
  'gradual', 'grammar', 'gravity', 'greater', 'greatly', 'grocery', 'growing', 'guarantee', 'guidance',
  'habitat', 'handful', 'harmony', 'heading', 'healthy', 'hearing', 'heavily', 'helpful', 'helping',
  'heritage', 'heroism', 'herself', 'highway', 'himself', 'history', 'holding', 'holiday', 'horizon',
  'hormone', 'hospital', 'housing', 'however', 'hundred', 'husband', 'identify', 'illegal', 'illness',
  'imagine', 'imaging', 'impacted', 'imperial', 'implement', 'importing', 'improve', 'incident',
  'included', 'increase', 'indicate', 'indirect', 'industry', 'infant', 'inform', 'initial', 'injury',
  'injustice', 'insight', 'insist', 'inspire', 'instance', 'instead', 'intense', 'interior', 'internal',
  'internet', 'interval', 'intimate', 'investor', 'involved', 'isolated', 'judgment', 'judicial',
  'junction', 'justice', 'justify', 'keeping', 'kingdom', 'kitchen', 'knocking', 'knowing', 'knowledge',
  'landing', 'largely', 'lasting', 'leading', 'learning', 'leasing', 'leather', 'lecture', 'legally',
  'leisure', 'lending', 'lengthy', 'liberal', 'liberty', 'license', 'limited', 'listing', 'literal',
  'literary', 'location', 'logical', 'loyalty', 'machine', 'magazine', 'magnetic', 'majority',
  'managing', 'manifest', 'mankind', 'manuals', 'mapping', 'marginal', 'marriage', 'massive',
  'matching', 'material', 'maturity', 'maximum', 'meaning', 'measure', 'mechanic', 'mediated',
  'medical', 'medicine', 'medieval', 'memorial', 'merchant', 'metallic', 'military', 'million',
  'minimize', 'minister', 'minority', 'miracle', 'missile', 'missing', 'mission', 'mistake',
  'mixture', 'mobility', 'moderate', 'modified', 'momentum', 'monetary', 'monitor', 'monster',
  'monthly', 'monument', 'mortgage', 'mountain', 'mounting', 'movement', 'multiple', 'multiply',
  'musical', 'musician', 'mutation', 'narrowly', 'national', 'native', 'naturally', 'necessity',
  'negative', 'neighbor', 'neither', 'nervous', 'network', 'neutral', 'newcomer', 'nineteen',
  'nominate', 'normally', 'northern', 'notebook', 'nothing', 'notified', 'november', 'nowadays',
  'nuisance', 'numerous', 'nutrient', 'objected', 'obstacle', 'obtained', 'obvious', 'occasion',
  'occupant', 'occurred', 'october', 'offering', 'official', 'offshore', 'ongoing', 'openness',
  'operable', 'operated', 'operator', 'opponent', 'opposite', 'optimism', 'optional', 'ordering',
  'ordinary', 'organism', 'original', 'outbreak', 'outcome', 'outdoors', 'outermost', 'outline',
  'outlook', 'outreach', 'outright', 'outsider', 'outward', 'overcome', 'overhead', 'overload',
  'overlook', 'overnight', 'overseas', 'overview', 'ownership', 'packages', 'painting', 'parallel',
  'paramount', 'parental', 'partial', 'partner', 'passage', 'passing', 'passion', 'passive',
  'pastoral', 'patience', 'patient', 'patronage', 'patterns', 'pavilion', 'peaceful', 'peasant',
  'peculiar', 'pedagogy', 'peerless', 'penalize', 'penalty', 'pendulum', 'penetrate', 'pension',
  'percent', 'perfect', 'perform', 'periodic', 'periphery', 'personal', 'persuade', 'petroleum',
  'pharmacy', 'phenomenon', 'philosophy', 'physical', 'pipeline', 'planning', 'platform', 'pleasant',
  'pleasure', 'plentiful', 'pointing', 'poisonous', 'polarity', 'policies', 'polishing', 'politely',
  'political', 'pollutant', 'popular', 'portable', 'portion', 'portrait', 'position', 'positive',
  'possible', 'postponed', 'potential', 'powerful', 'practice', 'precious', 'predict', 'prefer',
  'pregnant', 'premises', 'premium', 'prepare', 'presence', 'present', 'preserve', 'pressure',
  'prestige', 'previous', 'primary', 'priority', 'privacy', 'probable', 'problem', 'proceed',
  'process', 'produce', 'product', 'profile', 'profound', 'program', 'progress', 'project',
  'promise', 'promote', 'promptly', 'properly', 'property', 'proposal', 'proposed', 'prospect',
  'protect', 'protein', 'protest', 'protocol', 'provider', 'province', 'provoke', 'prudence',
  'publish', 'purchase', 'purpose', 'pursuing', 'qualified', 'quantity', 'quantum', 'quarrel',
  'quarter', 'question', 'quickly', 'quietly', 'quotient', 'radiation', 'radical', 'railroad',
  'rainbow', 'randomly', 'rapidity', 'rational', 'reaction', 'reactive', 'readily', 'reading',
  'realism', 'realize', 'rebuild', 'receipt', 'receiver', 'recently', 'recharge', 'recipe',
  'reckon', 'reclaim', 'recognize', 'recovery', 'recreation', 'recruiting', 'recurrent', 'redeem',
  'redesign', 'reducing', 'referee', 'referral', 'refining', 'reflect', 'reform', 'refugee',
  'refusing', 'regional', 'register', 'regular', 'regulate', 'rehearse', 'reinforce', 'reject',
  'relative', 'relaxing', 'relevant', 'reliable', 'reliance', 'religion', 'relocate', 'remain',
  'reminder', 'remnant', 'remotely', 'removal', 'renderer', 'renewing', 'repeated', 'replaced',
  'replica', 'reported', 'reporter', 'represent', 'republic', 'request', 'required', 'research',
  'resident', 'resource', 'respect', 'respond', 'response', 'restored', 'resulted', 'retainer',
  'retired', 'returned', 'revealed', 'revision', 'rewarding', 'rigorous', 'romantic', 'rotation',
  'routine', 'royalty', 'ruinous', 'safeguard', 'salvation', 'sampling', 'sanction', 'sandwich',
  'sanitary', 'sapphire', 'satellite', 'satisfy', 'scenario', 'schedule', 'scholar', 'science',
  'scooter', 'scramble', 'screening', 'sculpture', 'seamless', 'seasonal', 'secondly', 'security',
  'selected', 'sentence', 'separate', 'sequence', 'sergeant', 'serenity', 'servant', 'services',
  'settling', 'severity', 'shipment', 'shortcut', 'shoulder', 'shutdown', 'sidewalk', 'silence',
  'simplify', 'singular', 'skeleton', 'software', 'solution', 'somewhat', 'spectrum', 'standard',
  'strategy', 'strength', 'struggle', 'student', 'subject', 'substance', 'succeed', 'success',
  'suggest', 'suitable', 'superior', 'supplied', 'supplier', 'support', 'suppose', 'supreme',
  'surface', 'surgical', 'surprise', 'surround', 'survival', 'survivor', 'suspect', 'suspense',
  'symbolic', 'sympathy', 'syndrome', 'tactical', 'talented', 'tangible', 'taxation', 'taxonomy',
  'taxpayer', 'teaching', 'technique', 'telegram', 'template', 'temporal', 'tenant', 'tendency',
  'terminal', 'terrific', 'testimony', 'texture', 'thematic', 'theorem', 'theology', 'theorist',
  'thinking', 'thirteen', 'thorough', 'thousand', 'threshold', 'timeless', 'together', 'tolerance',
  'tomatoes', 'tomorrow', 'topography', 'totality', 'tracking', 'traction', 'trailing', 'training',
  'tranche', 'transfer', 'transform', 'transit', 'transmit', 'treasure', 'treating', 'treatise',
  'triangle', 'tribunal', 'tribute', 'triggers', 'triplets', 'triumph', 'tropical', 'tutorial',
  'twenties', 'twilight', 'ultimate', 'umbrella', 'unbiased', 'uncommon', 'undergo', 'underlie',
  'uniform', 'universe', 'unlawful', 'unlikely', 'unlocked', 'unpacked', 'unproven', 'unstable',
  'upgraded', 'uprising', 'upstream', 'urbanize', 'username', 'vacation', 'vaccine', 'validate',
  'valuable', 'variable', 'variance', 'variant', 'variety', 'velocity', 'venture', 'vertical',
  'veteran', 'vibrant', 'vicinity', 'victory', 'viewpoint', 'vigorous', 'village', 'violence',
  'virtual', 'visiting', 'visuals', 'vitality', 'vivacity', 'vocalist', 'volatile', 'volition',
  'volcano', 'volunteer', 'vouching', 'voyaging', 'vulnerable', 'warfare', 'warning', 'warrant',
  'warriors', 'wastage', 'watchful', 'waterfall', 'weakness', 'wealthy', 'wearable', 'weighted',
  'welcome', 'welfare', 'whatever', 'whenever', 'wherever', 'wholesome', 'wildlife', 'windfall',
  'wireless', 'withdraw', 'woodland', 'workshop', 'worthwhile', 'wreckage', 'wrestling', 'yearbook',
  'yielding', 'youthful', 'zealous',

  // Algorithm / Logarithm
  'algorithm', 'logarithm', 'creative', 'reactive'
];

export const FR_DICTIONARY: string[] = [
  // 2-letter words (French)
  'aa', 'ah', 'ai', 'an', 'as', 'au', 'ba', 'be', 'bi', 'bu', 'ca', 'ce', 'ci', 'da', 'de', 'do',
  'du', 'eh', 'en', 'es', 'et', 'eu', 'ex', 'fa', 'fi', 'ha', 'he', 'hi', 'ho', 'if', 'il', 'in',
  'je', 'ka', 'la', 'le', 'li', 'lu', 'ma', 'me', 'mi', 'mu', 'na', 'ne', 'ni', 'no', 'nu', 'oc',
  'oh', 'on', 'or', 'os', 'ou', 'pi', 'pu', 'ra', 're', 'ri', 'ru', 'sa', 'se', 'si', 'su', 'ta',
  'te', 'to', 'tu', 'un', 'us', 'va', 've', 'vs', 'vu', 'wu', 'xi',

  // 3-letter words (French)
  'ace', 'act', 'ada', 'ado', 'age', 'agi', 'aie', 'ail', 'air', 'ait', 'alu', 'ami', 'ane', 'ans',
  'api', 'app', 'arc', 'are', 'art', 'bac', 'bai', 'bal', 'ban', 'bar', 'bas', 'bat', 'bau', 'bay',
  'bec', 'bel', 'ben', 'ber', 'ble', 'boa', 'bob', 'bol', 'bon', 'bot', 'box', 'boy', 'bra', 'bue',
  'bus', 'but', 'cab', 'cal', 'cap', 'car', 'cas', 'ceb', 'cep', 'ces', 'cle', 'coi', 'col', 'con',
  'coq', 'cor', 'cou', 'cox', 'cri', 'cru', 'cul', 'dan', 'deb', 'des', 'dey', 'dia', 'din', 'dis',
  'dit', 'dix', 'doc', 'doh', 'dol', 'dom', 'don', 'dos', 'dot', 'dru', 'duc', 'due', 'duo', 'dur',
  'dus', 'dut', 'eau', 'ecu', 'ego', 'elu', 'eme', 'emu', 'epi', 'ere', 'erg', 'ers', 'est', 'eta',
  'ete', 'eue', 'eus', 'eut', 'eux', 'fac', 'fai', 'fan', 'far', 'fat', 'fax', 'fee', 'fer', 'feu',
  'fez', 'fia', 'fie', 'fil', 'fin', 'fit', 'foc', 'foi', 'fol', 'fou', 'fox', 'fur', 'fut', 'gag',
  'gai', 'gal', 'gan', 'gap', 'gar', 'gas', 'gay', 'gel', 'geo', 'gin', 'glu', 'gnu', 'gop', 'gos',
  'goy', 'gre', 'gui', 'gus', 'guy', 'gym', 'hai', 'han', 'hem', 'hep', 'heu', 'hie', 'hip', 'hit',
  'hop', 'hot', 'hou', 'hsp', 'hui', 'hum', 'hun', 'hup', 'hut', 'ici', 'ile', 'ils', 'ion', 'ira',
  'ire', 'iso', 'ive', 'ivs', 'jab', 'jam', 'jan', 'jar', 'jas', 'jet', 'jeu', 'job', 'joc', 'jou',
  'jus', 'kat', 'kea', 'ken', 'kgb', 'kid', 'kif', 'kir', 'kit', 'koa', 'kob', 'koi', 'kpi', 'ksu',
  'lac', 'lad', 'lai', 'lao', 'las', 'lec', 'led', 'leg', 'lei', 'lek', 'les', 'let', 'leu', 'lev',
  'lez', 'lia', 'lie', 'lin', 'lis', 'lit', 'lob', 'loi', 'los', 'lot', 'lou', 'luc', 'lue', 'lui',
  'lus', 'lut', 'lux', 'lys', 'mac', 'mai', 'mal', 'man', 'mao', 'mar', 'mas', 'mat', 'mec', 'mel',
  'mer', 'mes', 'met', 'mie', 'mil', 'min', 'mir', 'mis', 'mit', 'mix', 'moi', 'mol', 'mon', 'mor',
  'mot', 'mou', 'mox', 'mua', 'mue', 'mug', 'mur', 'mus', 'mut', 'mys', 'nac', 'nan', 'nao', 'nba',
  'nee', 'nef', 'nem', 'neo', 'nes', 'net', 'ney', 'nez', 'nid', 'nie', 'nil', 'nim', 'nom', 'non',
  'nos', 'nou', 'nul', 'oie', 'oik', 'oil', 'ois', 'oit', 'oli', 'oms', 'ont', 'ooc', 'ooh', 'opa',
  'opt', 'orq', 'ort', 'ost', 'ota', 'ote', 'oui', 'out', 'ove', 'oye', 'pac', 'paf', 'pai', 'pal',
  'pan', 'pap', 'par', 'pas', 'pat', 'pau', 'pax', 'pay', 'pec', 'peg', 'pel', 'pen', 'pep', 'per',
  'pes', 'pet', 'peu', 'pfi', 'phi', 'pho', 'pia', 'pic', 'pie', 'pif', 'pin', 'pis', 'pli', 'plu',
  'pog', 'poi', 'pol', 'pom', 'pop', 'pot', 'pou', 'pre', 'pro', 'psi', 'pst', 'psu', 'pua', 'pub',
  'pue', 'pui', 'pun', 'pur', 'pus', 'put', 'puy', 'rab', 'rac', 'rad', 'rai', 'raj', 'ram', 'rap',
  'ras', 'rat', 'ray', 'raz', 'reb', 'rec', 'ree', 'ref', 'reg', 'rei', 'rem', 'reo', 'rep', 'res',
  'rez', 'rha', 'ria', 'rib', 'rie', 'rif', 'rio', 'rip', 'ris', 'rit', 'rob', 'roc', 'roi', 'rom',
  'ron', 'rot', 'rou', 'rox', 'roy', 'rue', 'rug', 'rus', 'rut', 'rye', 'sac', 'sai', 'sal', 'sam',
  'san', 'sap', 'sas', 'sax', 'sec', 'sel', 'sen', 'sep', 'ser', 'ses', 'set', 'sic', 'sil', 'sir',
  'six', 'ski', 'sol', 'son', 'sot', 'sou', 'spa', 'spi', 'str', 'sue', 'suf', 'sur', 'sus', 'sut',
  'tac', 'tag', 'tai', 'tan', 'tao', 'tap', 'tar', 'tas', 'tat', 'tau', 'tec', 'tee', 'tel', 'ter',
  'tes', 'tet', 'tex', 'the', 'tia', 'tic', 'tif', 'tin', 'tip', 'tir', 'tis', 'tit', 'toc', 'toi',
  'tom', 'ton', 'top', 'tor', 'tos', 'tot', 'tou', 'tri', 'tro', 'tru', 'tsa', 'tse', 'tue', 'tuf',
  'tui', 'tur', 'tus', 'tut', 'tux', 'typ', 'une', 'uns', 'urd', 'ure', 'urs', 'usa', 'use', 'ute',
  'val', 'van', 'var', 'vas', 'vau', 'vax', 'vee', 'ver', 'ves', 'vet', 'via', 'vie', 'vif', 'vil',
  'vin', 'vis', 'vit', 'vol', 'vos', 'vou', 'vue', 'vus', 'wap', 'wax', 'web', 'wok', 'won', 'yen',
  'yeu', 'yod', 'zam', 'zar', 'zec', 'zee', 'zek', 'zen', 'zig', 'zip', 'zob', 'zoe', 'zoo',

  // 4-letter words (French)
  'abri', 'acte', 'afin', 'aide', 'aile', 'aime', 'ains', 'aise', 'alla', 'alle', 'alma', 'alpe',
  'ames', 'amie', 'amis', 'ange', 'anse', 'aout', 'apte', 'arba', 'arch', 'arcs', 'ares', 'aria',
  'arme', 'arts', 'asse', 'atre', 'aube', 'aura', 'auto', 'avec', 'avez', 'avis', 'axer', 'axes',
  'baie', 'bain', 'bale', 'banc', 'bard', 'base', 'bata', 'bate', 'beau', 'bebe', 'befe', 'beni',
  'bete', 'bien', 'bile', 'bise', 'bleu', 'bloc', 'boir', 'bois', 'boit', 'bonn', 'bons', 'bord',
  'bose', 'bote', 'boue', 'bout', 'bras', 'bref', 'brin', 'brio', 'brut', 'buis', 'bull', 'buse',
  'cade', 'cafe', 'cage', 'camp', 'cane', 'cape', 'caps', 'cars', 'case', 'cave', 'ceci', 'cela',
  'cene', 'cent', 'cerf', 'ceux', 'char', 'chef', 'cher', 'chez', 'chou', 'ciel', 'cima', 'cine',
  'cinq', 'cire', 'cite', 'clef', 'clou', 'club', 'coin', 'cois', 'cola', 'cols', 'coma', 'cone',
  'coqf', 'cops', 'coqs', 'cord', 'corn', 'corps', 'cote', 'cots', 'coup', 'cour', 'cout', 'crau',
  'cric', 'crin', 'cris', 'crit', 'croc', 'cuir', 'cuis', 'cuit', 'cure', 'cuve', 'daim', 'dame',
  'dans', 'date', 'deca', 'deja', 'demi', 'dent', 'deux', 'dieu', 'dime', 'dina', 'dine', 'dira',
  'dire', 'dise', 'dite', 'dits', 'dock', 'dodu', 'dodo', 'doit', 'dole', 'dome', 'donc', 'dons',
  'dont', 'dore', 'dors', 'dort', 'dose', 'dota', 'dote', 'doue', 'doux', 'drap', 'droit', 'drue',
  'ducs', 'duel', 'dues', 'dune', 'duos', 'dupe', 'dura', 'dure', 'durs', 'eaux', 'echa', 'echo',
  'ecke', 'eclat', 'ecot', 'ecru', 'ecus', 'eden', 'egal', 'ehre', 'elan', 'elba', 'elfe', 'elue',
  'elus', 'emoi', 'emus', 'encre', 'epee', 'epis', 'epre', 'ergs', 'erre', 'etas', 'etat', 'etes',
  'etre', 'eues', 'euro', 'evas', 'evoe', 'exon', 'face', 'fade', 'faim', 'fais', 'fait', 'fame',
  'faon', 'fard', 'fart', 'faut', 'faux', 'faye', 'feve', 'fief', 'fier', 'fies', 'fieu', 'file',
  'fils', 'fina', 'fine', 'fins', 'fion', 'fisc', 'fits', 'fixe', 'flan', 'flic', 'floc', 'flot',
  'flou', 'flux', 'foie', 'foin', 'fois', 'fols', 'fond', 'font', 'foot', 'fore', 'fort', 'foss',
  'fous', 'fout', 'frais', 'fret', 'fric', 'froc', 'froid', 'fuel', 'fuie', 'fuir', 'fuis', 'fuit',
  'fume', 'fusa', 'fuse', 'futa', 'fute', 'futs', 'gain', 'gala', 'gale', 'gang', 'gant', 'gara',
  'gare', 'gars', 'gate', 'gats', 'gaze', 'geai', 'gele', 'gels', 'gene', 'gens', 'giga', 'gite',
  'glae', 'glas', 'glen', 'glou', 'glua', 'glue', 'goba', 'gobe', 'golf', 'gond', 'gong', 'gord',
  'gout', 'gras', 'grec', 'gres', 'gros', 'grue', 'guee', 'gues', 'guid', 'hale', 'halo', 'hart',
  'hate', 'haut', 'havr', 'hein', 'held', 'hero', 'hier', 'hifi', 'hiva', 'hocs', 'hoir', 'home',
  'hors', 'host', 'hote', 'houe', 'houx', 'huas', 'huat', 'huer', 'hues', 'huit', 'hune', 'huos',
  'hure', 'huss', 'huts', 'hyne', 'hyso', 'iamb', 'ibex', 'ibis', 'icon', 'idee', 'idem', 'iles',
  'ilet', 'ilot', 'imam', 'inde', 'indi', 'infa', 'info', 'inox', 'inri', 'iota', 'irai', 'iras',
  'ires', 'irez', 'iris', 'isba', 'isol', 'issu', 'item', 'ivra', 'ivre', 'ixia', 'ixod', 'jabs',
  'jaco', 'jact', 'jade', 'jais', 'jale', 'jamb', 'jant', 'jard', 'jars', 'jase', 'jasp', 'jave',
  'jeep', 'jerk', 'jeta', 'jete', 'jets', 'jeux', 'jive', 'jobs', 'joie', 'joli', 'jonc', 'joua',
  'joue', 'joug', 'joui', 'jour', 'jube', 'juda', 'judo', 'juge', 'juif', 'juin', 'jupe', 'jura',
  'jure', 'jury', 'juta', 'jute', 'kadi', 'kaki', 'kami', 'kaon', 'kart', 'kava', 'kawa', 'kepi',
  'khan', 'khol', 'kifa', 'kife', 'kifs', 'kilo', 'kilt', 'kipa', 'kips', 'kiva', 'klax', 'koan',
  'kobo', 'koka', 'kope', 'kora', 'kore', 'kota', 'kote', 'kots', 'koul', 'krak', 'krul', 'kudo',
  'kula', 'kurf', 'kvas', 'kyat', 'kyli', 'kyte', 'lace', 'lacs', 'lacs', 'lady', 'laie', 'laid',
  'lait', 'lama', 'lamb', 'lame', 'land', 'laos', 'lard', 'lare', 'larg', 'laur', 'lava', 'lave',
  'laya', 'laye', 'lead', 'lege', 'legs', 'lent', 'lest', 'leur', 'leve', 'liai', 'lias', 'liat',
  'lier', 'lies', 'lieu', 'liez', 'lift', 'lige', 'lima', 'lime', 'lino', 'lins', 'lion', 'lire',
  'lise', 'lisp', 'lits', 'live', 'livr', 'lobe', 'lobi', 'lobs', 'loch', 'loci', 'loco', 'lods',
  'loft', 'loge', 'logo', 'loin', 'loir', 'lois', 'lolo', 'lone', 'long', 'look', 'lord', 'lors',
  'lote', 'loti', 'loto', 'lots', 'loua', 'loue', 'loup', 'lowa', 'loya', 'luau', 'luba', 'lues',
  'luge', 'luis', 'luit', 'lulu', 'luma', 'lump', 'lune', 'luos', 'luta', 'lute', 'luth', 'luts',
  'luxe', 'lynx', 'lyra', 'lyre', 'lysa', 'lyse', 'mach', 'macs', 'mafi', 'mage', 'magi', 'maie',
  'mail', 'main', 'mais', 'maje', 'maki', 'male', 'mali', 'mals', 'malt', 'mame', 'mamy', 'mana',
  'mani', 'mans', 'maos', 'maou', 'mara', 'marc', 'mare', 'mari', 'mark', 'mars', 'masa', 'mase',
  'masq', 'mata', 'mate', 'math', 'mati', 'mats', 'matu', 'maud', 'maux', 'maxi', 'maya', 'maye',
  'mays', 'maze', 'mean', 'meats', 'meba', 'mech', 'mede', 'medi', 'mela', 'mele', 'melo', 'mels',
  'meme', 'mena', 'mene', 'mens', 'ment', 'menu', 'meos', 'mere', 'meri', 'mesa', 'mese', 'mess',
  'meta', 'mets', 'meuh', 'meus', 'meut', 'miao', 'mica', 'midi', 'miel', 'mien', 'mies', 'mieu',
  'mifa', 'migs', 'mile', 'mils', 'mima', 'mime', 'mina', 'mine', 'mini', 'mira', 'mire', 'miro',
  'mirs', 'misa', 'mise', 'miso', 'miss', 'mita', 'mite', 'mixa', 'mixe', 'moby', 'moco', 'mode',
  'moha', 'moho', 'moie', 'moir', 'mois', 'moka', 'moko', 'mola', 'mole', 'moly', 'mome', 'momi',
  'momo', 'mona', 'mone', 'mons', 'mont', 'mook', 'moor', 'mops', 'mora', 'mord', 'more', 'morf',
  'mori', 'moro', 'mors', 'mort', 'mota', 'mote', 'moto', 'mots', 'mott', 'mou', 'moud', 'moue',
  'mouf', 'mous', 'mout', 'moxa', 'moye', 'muai', 'muas', 'muat', 'muck', 'muer', 'mues', 'muet',
  'muez', 'mugi', 'mugs', 'mula', 'mule', 'mull', 'mulo', 'muls', 'mult', 'mura', 'mure', 'muri',
  'murs', 'musa', 'muse', 'musk', 'muso', 'musq', 'must', 'muta', 'mute', 'muts', 'myri', 'myrt',
  'myso', 'myte', 'naan', 'naba', 'nabe', 'nabi', 'nabs', 'nach', 'naja', 'nana', 'nans', 'nant',
  'naos', 'nard', 'nase', 'nazi', 'nees', 'nefs', 'nein', 'nems', 'nene', 'neon', 'nerf', 'nerv',
  'nets', 'neuf', 'neve', 'news', 'niai', 'nias', 'niat', 'nibe', 'nica', 'nida', 'nids', 'nier',
  'nies', 'niez', 'niga', 'nixe', 'noce', 'noel', 'noir', 'noix', 'noma', 'nome', 'noms', 'none',
  'nord', 'nori', 'norm', 'nota', 'note', 'noua', 'noue', 'nous', 'nova', 'nove', 'novi', 'novo',
  'noya', 'noye', 'nuai', 'nuas', 'nuat', 'nuba', 'nuer', 'nues', 'nuez', 'nuis', 'nuit', 'nuls',
  'obel', 'obis', 'obit', 'oboi', 'oboe', 'obus', 'ocra', 'ocre', 'octa', 'octo', 'odes', 'oeil',
  'oeuf', 'ogre', 'ohio', 'oies', 'oins', 'oint', 'olla', 'omra', 'once', 'onde', 'onze', 'opale',
  'open', 'opes', 'opte', 'opts', 'opus', 'orbe', 'ores', 'orge', 'orin', 'orle', 'orme', 'orve',
  'osai', 'osas', 'osat', 'oser', 'oses', 'osez', 'osid', 'otai', 'otas', 'otat', 'oter', 'otes',
  'otez', 'ouah', 'oued', 'ouie', 'ouir', 'ouis', 'ouit', 'oups', 'ours', 'ouzo', 'ouvr', 'oxer',
  'oxyd', 'oyes', 'oyez', 'ozon', 'paas', 'pacs', 'paga', 'page', 'pagi', 'paie', 'pain', 'pair',
  'pais', 'pait', 'paix', 'pala', 'pale', 'pali', 'pals', 'pana', 'pane', 'pans', 'paon', 'papa',
  'pape', 'papi', 'papy', 'para', 'parc', 'pare', 'pari', 'pars', 'part', 'paru', 'pass', 'pata',
  'pate', 'pati', 'pats', 'paty', 'paue', 'paum', 'pava', 'pave', 'paye', 'pays', 'peau', 'peba',
  'pech', 'pega', 'pegs', 'pehl', 'pein', 'pela', 'pele', 'peli', 'pels', 'pene', 'peni', 'pens',
  'peon', 'pepe', 'pepi', 'peps', 'perb', 'perd', 'pere', 'perf', 'peri', 'perm', 'pers', 'pese',
  'peso', 'pest', 'peta', 'pete', 'peti', 'pets', 'peuf', 'peuh', 'peul', 'peur', 'peut', 'peux',
  'phos', 'phot', 'pica', 'pich', 'pics', 'pied', 'pien', 'pies', 'pieu', 'pifa', 'pife', 'pifs',
  'pige', 'pila', 'pile', 'pils', 'pima', 'pina', 'pine', 'ping', 'pins', 'pion', 'pipa', 'pipe',
  'pipi', 'pipo', 'pire', 'pisa', 'pise', 'piss', 'pita', 'pite', 'piti', 'pive', 'piwi', 'plan',
  'plat', 'plia', 'plie', 'plis', 'plot', 'plug', 'plui', 'plum', 'plus', 'plut', 'pneu', 'pocs',
  'poil', 'poin', 'pois', 'poit', 'poke', 'pola', 'pole', 'poli', 'polo', 'pols', 'poly', 'pome',
  'pomme', 'pomp', 'pont', 'pool', 'pope', 'pops', 'porc', 'pore', 'pors', 'port', 'posa', 'pose',
  'post', 'pote', 'pots', 'pouf', 'poul', 'poup', 'pour', 'pout', 'poux', 'prao', 'pres', 'pret',
  'pria', 'prie', 'pris', 'prit', 'prix', 'proc', 'prof', 'prog', 'proi', 'prom', 'prop', 'prou',
  'prun', 'pruy', 'pshi', 'psts', 'puai', 'puas', 'puat', 'puce', 'puer', 'pues', 'puez', 'puis',
  'puja', 'pula', 'pull', 'pulp', 'puma', 'puni', 'punk', 'pupa', 'pupe', 'pure', 'puri', 'purs',
  'pute', 'puts', 'puys', 'pyle', 'pyre', 'pyro', 'quad', 'quai', 'quas', 'quel', 'quia', 'quid',
  'quiz', 'quoi', 'quot', 'rabe', 'rabi', 'rabs', 'raca', 'race', 'rack', 'rada', 'rade', 'rads',
  'rafe', 'raft', 'raga', 'rage', 'raia', 'raid', 'raie', 'rail', 'rais', 'raja', 'raki', 'raku',
  'rala', 'rale', 'rama', 'rame', 'rami', 'ramp', 'rams', 'rang', 'rani', 'rapa', 'rape', 'raps',
  'rapt', 'rare', 'rasa', 'rase', 'rash', 'rass', 'rata', 'rate', 'rats', 'rave', 'ravi', 'raya',
  'raye', 'rays', 'reai', 'reas', 'reat', 'rebe', 'rebu', 'reca', 'reco', 'recu', 'reer', 'rees',
  'reez', 'refs', 'regi', 'regs', 'rein', 'reis', 'reja', 'rele', 'relo', 'rems', 'rend', 'rene',
  'reng', 'reni', 'renk', 'reno', 'rent', 'reos', 'repa', 'repi', 'repo', 'reps', 'repu', 'reso',
  'rest', 'reto', 'rets', 'reva', 'reve', 'revu', 'rhea', 'rhum', 'rial', 'rias', 'ribs', 'rice',
  'rich', 'riel', 'rien', 'ries', 'riez', 'rifs', 'rift', 'rima', 'rime', 'ring', 'rins', 'rio',
  'rios', 'ripa', 'ripe', 'rips', 'rira', 'rire', 'rise', 'risi', 'risq', 'rite', 'riva', 'rive',
  'rixe', 'riad', 'robe', 'robs', 'rocs', 'roda', 'rode', 'rois', 'role', 'romb', 'rome', 'romp',
  'rond', 'roof', 'rore', 'rosa', 'rose', 'rosi', 'rota', 'rote', 'roti', 'roto', 'rots', 'roua',
  'roue', 'rouf', 'roug', 'roui', 'roul', 'roux', 'roya', 'roye', 'ruai', 'ruas', 'ruat', 'rube',
  'rubs', 'rude', 'rudi', 'ruer', 'rues', 'ruez', 'rugi', 'ruin', 'ruiz', 'rule', 'ruma', 'rumb',
  'rune', 'ruos', 'rupa', 'rupe', 'rusa', 'ruse', 'rush', 'rust', 'ruta', 'rute', 'ruts', 'ryad',
  'ryal', 'ryes', 'saas', 'sabe', 'sabi', 'sabs', 'saca', 'sach', 'sacs', 'saga', 'sage', 'sago',
  'saie', 'sail', 'sain', 'sais', 'sait', 'sake', 'saki', 'sala', 'sale', 'sali', 'sals', 'same',
  'sami', 'sana', 'sand', 'sang', 'sans', 'sant', 'sapa', 'sape', 'saps', 'sara', 'sard', 'sari',
  'sart', 'sasa', 'sati', 'sats', 'sauf', 'saur', 'saut', 'saux', 'sava', 'save', 'saxo', 'saye',
  'scat', 'scia', 'scie', 'scot', 'seam', 'seau', 'sebs', 'seca', 'sech', 'secs', 'sect', 'sega',
  'segs', 'sein', 'seis', 'sele', 'self', 'sels', 'sema', 'seme', 'semi', 'sene', 'sens', 'sent',
  'sepe', 'seps', 'sera', 'serb', 'serf', 'sers', 'sert', 'sese', 'sete', 'sets', 'seue', 'seul',
  'seus', 'seut', 'seve', 'sexe', 'sexy', 'shah', 'shed', 'shil', 'shin', 'ship', 'shot', 'show',
  'siam', 'sica', 'sida', 'sidi', 'sien', 'sies', 'siff', 'sige', 'sika', 'sile', 'sils', 'sima',
  'simp', 'sinc', 'sine', 'sing', 'sinh', 'sino', 'sins', 'sire', 'sise', 'sita', 'site', 'sits',
  'situ', 'sium', 'siva', 'sive', 'sixi', 'sixt', 'skai', 'skas', 'skat', 'skia', 'skie', 'skif',
  'skin', 'skip', 'skis', 'skol', 'skua', 'slam', 'slip', 'slow', 'smal', 'smar', 'smic', 'smog',
  'smol', 'smut', 'snak', 'snif', 'snob', 'soda', 'sode', 'sofa', 'soie', 'soif', 'soin', 'soir',
  'sois', 'soit', 'soja', 'sola', 'sold', 'sole', 'soli', 'solo', 'sols', 'soma', 'some', 'somm',
  'sone', 'song', 'sons', 'sont', 'sope', 'sora', 'sorb', 'sore', 'sort', 'sosa', 'soso', 'sots',
  'soue', 'souf', 'souk', 'soul', 'soum', 'soup', 'sour', 'sous', 'soya', 'soys', 'spas', 'spat',
  'spec', 'spic', 'spin', 'spis', 'spit', 'spol', 'spot', 'spru', 'stad', 'star', 'stem', 'step',
  'stew', 'stil', 'stop', 'stot', 'stot', 'stra', 'stuc', 'stud', 'stuf', 'stur', 'suai', 'suas',
  'suat', 'subi', 'subs', 'succ', 'suce', 'suco', 'sucs', 'suda', 'sude', 'suds', 'suer', 'sues',
  'suez', 'suie', 'suif', 'suis', 'suit', 'suiv', 'suje', 'sulf', 'sulu', 'sumi', 'sumo', 'suni',
  'supe', 'supr', 'sura', 'sure', 'surf', 'surg', 'suri', 'suro', 'surs', 'surt', 'sush', 'susp',
  'sute', 'suts', 'svas', 'swap', 'swat', 'swin', 'syce', 'syli', 'symb', 'syph', 'syra', 'syre',
  'taal', 'taba', 'tabi', 'tabs', 'tabu', 'taca', 'tace', 'tach', 'tack', 'taco', 'tacs', 'tact',
  'tael', 'taff', 'tafs', 'tage', 'tagi', 'tags', 'taia', 'taie', 'tail', 'tain', 'tais', 'tait',
  'taka', 'take', 'taki', 'taks', 'tala', 'talc', 'tale', 'tali', 'talo', 'tals', 'tama', 'tame',
  'tami', 'tamp', 'tams', 'tana', 'tand', 'tane', 'tang', 'tanh', 'tani', 'tank', 'tann', 'tans',
  'tant', 'taos', 'tapa', 'tape', 'tapi', 'tapo', 'taps', 'tara', 'tard', 'tare', 'tari', 'taro',
  'tars', 'tart', 'tasa', 'tase', 'task', 'tass', 'tata', 'tate', 'tati', 'tato', 'tats', 'tatu',
  'taud', 'taup', 'taur', 'taus', 'taux', 'tava', 'taxa', 'taxe', 'taxi', 'taye', 'tays', 'tcha',
  'tche', 'tchi', 'tchu', 'team', 'teau', 'teba', 'tech', 'tect', 'tedi', 'tees', 'teff', 'tefs',
  'tege', 'teia', 'teie', 'tein', 'teis', 'teit', 'teju', 'teks', 'tela', 'tele', 'tell', 'tels',
  'tema', 'teme', 'temp', 'tend', 'teni', 'teno', 'tens', 'tent', 'tenu', 'teos', 'tepa', 'tepe',
  'tera', 'terf', 'term', 'tern', 'ters', 'tert', 'test', 'tete', 'tets', 'tett', 'tetz', 'teuf',
  'teve', 'tewa', 'texa', 'text', 'thas', 'thee', 'thei', 'theo', 'thes', 'thia', 'thie', 'thio',
  'thon', 'thos', 'thug', 'thus', 'thyl', 'thym', 'tian', 'tias', 'tibi', 'tibs', 'tics', 'tide',
  'tief', 'tied', 'tien', 'tiet', 'tieu', 'tife', 'tifs', 'tige', 'tigo', 'tigs', 'tika', 'tike',
  'tiki', 'tiks', 'tila', 'tile', 'tili', 'tils', 'tilt', 'tima', 'time', 'timi', 'tims', 'tina',
  'tine', 'tini', 'tino', 'tins', 'tint', 'tios', 'tipa', 'tipe', 'tipi', 'tipo', 'tips', 'tira',
  'tire', 'tiri', 'tiro', 'tirs', 'tisa', 'tise', 'tiso', 'tiss', 'titi', 'tits', 'titu', 'tius',
  'toar', 'toas', 'toat', 'toby', 'toca', 'toce', 'toch', 'toco', 'tocs', 'toer', 'toes', 'toez',
  'tofe', 'tofs', 'tofu', 'toga', 'toge', 'togo', 'toie', 'toil', 'toin', 'tois', 'toit', 'toja',
  'toke', 'toko', 'toks', 'tola', 'tole', 'toli', 'toll', 'tolo', 'tols', 'toma', 'tomb', 'tome',
  'tomi', 'toms', 'tonc', 'tond', 'tone', 'tong', 'toni', 'tonk', 'tons', 'tonu', 'topa', 'tope',
  'topi', 'topo', 'tops', 'toqu', 'tora', 'torc', 'tord', 'tore', 'tori', 'tork', 'torm', 'torn',
  'toro', 'torp', 'torr', 'tors', 'tort', 'toru', 'torx', 'tory', 'tosa', 'tose', 'tosi', 'toss',
  'tota', 'tote', 'toti', 'toto', 'tots', 'toua', 'toue', 'touf', 'toui', 'touk', 'toul', 'toun',
  'toup', 'tour', 'tous', 'tout', 'toxo', 'toyo', 'toys', 'toza', 'toze', 'trac', 'trad', 'trak',
  'tram', 'trap', 'trar', 'tras', 'trat', 'trau', 'tray', 'tref', 'trei', 'trek', 'trem', 'tren',
  'tres', 'tret', 'treu', 'trev', 'tria', 'trib', 'tric', 'trie', 'trig', 'trim', 'trin', 'trio',
  'trip', 'tris', 'trit', 'troc', 'trod', 'trog', 'troi', 'trol', 'trom', 'tron', 'trop', 'trot',
  'trou', 'trov', 'troy', 'truc', 'trud', 'true', 'truf', 'trug', 'trui', 'trum', 'trun', 'trup',
  'trus', 'tsar', 'tsas', 'tsee', 'tses', 'tshu', 'tsim', 'tsis', 'tsou', 'tsun', 'tsva', 'tuai',
  'tuas', 'tuat', 'tuba', 'tube', 'tubs', 'tuca', 'tuch', 'tucs', 'tude', 'tuer', 'tues', 'tuez',
  'tufa', 'tufe', 'tuff', 'tufs', 'tuge', 'tugs', 'tuhu', 'tuie', 'tuil', 'tuis', 'tuit', 'tula',
  'tule', 'tuli', 'tuls', 'tuna', 'tune', 'tung', 'tuni', 'tunk', 'tuns', 'tupa', 'tupi', 'tups',
  'tura', 'turc', 'turd', 'ture', 'turf', 'turi', 'turk', 'turl', 'turn', 'turo', 'turp', 'turs',
  'turt', 'tusa', 'tuse', 'tush', 'tuss', 'tuta', 'tute', 'tuti', 'tuto', 'tuts', 'tutu', 'tuvs',
  'tuya', 'tuyu', 'tvas', 'tver', 'twat', 'twee', 'twig', 'twin', 'twit', 'twos', 'tyee', 'tyke',
  'tylo', 'tyna', 'tyne', 'typa', 'type', 'typi', 'typo', 'typs', 'tyra', 'tyre', 'tyro', 'tzar',

  // 5-letter & 6-letter & 7-letter French Anagram Targets
  'abricot', 'aimer', 'aimons', 'ancetre', 'animaux', 'arbre', 'argent', 'artisan', 'artiste',
  'bateau', 'blanche', 'bonjour', 'boulot', 'cadence', 'carnet', 'cascade', 'cerise', 'chambre',
  'chasser', 'chateau', 'chemin', 'cheval', 'chien', 'chine', 'cinema', 'citron', 'classe', 'cloche',
  'courage', 'creatif', 'cuisine', 'demain', 'dessin', 'disque', 'dormir', 'ecole', 'ecouter', 'enfant',
  'entree', 'epaule', 'espace', 'etoile', 'famille', 'fenetre', 'feuille', 'flamme', 'fleur', 'foret',
  'fraise', 'framboise', 'fromage', 'garcon', 'gateau', 'guitare', 'histoire', 'homme', 'horizon',
  'horloge', 'image', 'jardin', 'journal', 'lampe', 'lecture', 'lettre', 'liberte', 'livre', 'lumiere',
  'maison', 'manoir', 'marche', 'matin', 'melodie', 'memoire', 'minute', 'miroir', 'monde', 'musique',
  'nature', 'navire', 'neige', 'niche', 'oiseau', 'orange', 'papier', 'pardon', 'paris', 'parole',
  'pensif', 'pensee', 'pierre', 'plage', 'planete', 'plante', 'poeme', 'poesie', 'pomme', 'porte',
  'potier', 'poule', 'poulet', 'prince', 'prison', 'racine', 'raisin', 'regard', 'riviere', 'saison',
  'secret', 'silence', 'soleil', 'sommeil', 'source', 'souris', 'table', 'temple', 'terroir', 'theatre',
  'tomate', 'toupie', 'travail', 'tresor', 'tulipe', 'vacance', 'valise', 'vapeur', 'vecteur', 'verite',
  'village', 'visage', 'vision', 'voiture', 'voyage', 'zenith',
  // Specific Anagram Pairs
  'paris', 'pairs', 'prais', 'prias', 'ripas',
  'chien', 'niche', 'chine', 'echin',
  'maison', 'aimons',
  'artisan', 'tsarina',
  'listen', 'silent', 'enlist', 'tinsel', 'inlets'
];
